name: Check Tablón URJC

on:
  schedule:
    - cron: "0 7,13 * * 1-5"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python check_tablon.py

      - name: Sync con remote
        run: git pull --rebase origin main

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update last_seen"
          file_pattern: last_seen.txt
